### ISSUE TITLE
Early supporter packs not recognized

### ISSUE THREAD

**Issue by antoine-fresse** [DanielTaranger/poeTransactionCounter#13]
Hello, for me the early supporter packs are not recognized 

![image](https://github.com/user-attachments/assets/f5e3b27f-7b4d-42db-92a8-ef43f2b9ed9a)
![image](https://github.com/user-attachments/assets/3394a34e-d6ce-42da-afbc-bc436d6615b1)

**Comment by DanielTaranger** [comment]
Anyone know the costs of these packs? Should be easy also to just create a pullrequest on it too

**Comment by peeteer1245** [comment]
The Wiki has a [list of all Supporter Packs](https://www.poewiki.net/wiki/Supporter_pack).
There you can dig down into the individual Series.

**Comment by Nightblade** [comment]
The wiki appears to have added word `Supporter` into the names which stops the script from working.  For example:
Wiki:  `Bronze Supporter Pack`  PoE:  `Bronze Pack`
