### ISSUE TITLE
Uncaught SyntaxError: unexpected token: identifier

### ISSUE THREAD

**Issue by stefanw1337** [DanielTaranger/poeTransactionCounter#17]
I followed the instructions. Using Firefox. Got error:
`Uncaught SyntaxError: unexpected token: identifier`

I have no idea what this means, I don't think I did it wrong. I went to the console, but I had to type "allow pasting" first, CTRL+Enter to run the line I copied.

**Comment by Sol3337** [comment]
Unexpected token '%' is what I got myself

**Comment by DanielTaranger** [comment]
Tested in firefox myself, works for me, make sure to type allow paste in console in firefox before pasting
