### ISSUE TITLE
Original Kickstarter packs missing

### ISSUE THREAD

**Issue by ransagy** [DanielTaranger/poeTransactionCounter#30]
In my case, the Diamond Supporter pack (1K USD tier in KS).

**Comment by DanielTaranger** [comment]
i need the exact error you got. "xxxx pack not found" so I can add it and exact price

**Comment by ransagy** [comment]
"Pack not found:
 Diamond Pack"
 
 in the dialog that pops up.
 
"The following supporter packs are unaccounted for... 
Diamond Pack"

In the dev console.

**Comment by DanielTaranger** [comment]
Thanks! Fixed it
*Daniel Taranger*
 EDM Production
facebook <https://www.facebook.com/nadenofficial>  |  twitter
<https://twitter.com/NadenOfficial>  |  soundcloud
<https://soundcloud.com/naden>


tir. 26. nov. 2024 kl. 18:26 skrev Ran Sagy ***@***.***>:
