### ISSUE TITLE
Zealot's Penance Supporter Pack price wrong

### ISSUE THREAD

**Issue by kangdu** [DanielTaranger/poeTransactionCounter#32]
the script gives out "Zealot's Penance Supporter Pack ($30)"

but it;s actually $90. Below are the system msg to my account"

"
Your order number is: 
You have ordered: Zealot&#039;s Penance Supporter Pack
Total cost: 90USD
"

**Comment by DanielTaranger** [comment]
@peeteer1245  is this something you could take a look at and find a solution for?

**Comment by peeteer1245** [comment]
Sure.

**Comment by cahrin** [comment]
https://github.com/DanielTaranger/poeTransactionCounter/pull/33

**Comment by DanielTaranger** [comment]
Splendid!
