### ISSUE TITLE
"Gemling Artificier" Mispelling

### ISSUE THREAD

**Issue by TheBackstabi** [DanielTaranger/poeTransactionCounter#35]
"Gemling Artificier" is not in the script, but rather "Gemling Artificer". Unsure if this is for all versions of it, or just some.

![image](https://github.com/user-attachments/assets/0ba2b7ee-9fcc-4502-bb82-b9b7dc87b9bb)

![image](https://github.com/user-attachments/assets/8545a804-bc7d-43b8-a354-7f7fcd7aad1d)

**Comment by DanielTaranger** [comment]
Should be ok, please confirm

**Comment by TheBackstabi** [comment]
Looks good now
